compressionLevel: mixed

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

packageExtensions:
  eslint-config-next@*:
    dependencies:
      next: "*"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
