apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zicdding-front-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Zicdding/zicdding-class.git'
    targetRevision: main
    path: 'frontend/zicdding-class.com/k8s/manifests'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true