apiVersion: apps/v1
kind: Deployment
metadata:
  name: zicdding-front-app
  labels:
    app: front-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
      - name: zicdding-front-app
        image: ${{ secrets.DOCKER_USERNAME }}/zicdding-front:latest
        ports:
        - containerPort: 3000